"""What SHAPES do rules actually have, and what generates them? (§12, §20)

The question this answers is whether a corpus needs the rule language at all, or
whether most knowledge could be **facts** filling a small set of bundled schema
rules -- and, if rules are needed, how many distinct kinds.

Four measurements, and the second refuted the conclusion the first suggested:

  1. the shape census over every corpus the suite exercises
  2. the same over EXTERNAL corpora, where the fixture skew is absent
  3. what the surface will and will not express (§5's wall, probed not read)
  4. that high arity and dense joins are GENERATED by composing 2-member rules

⚠ The headline from (1) alone -- *five shapes cover 89.5%* -- is true and
misleading. Almost all of those rules are GENERIC, and a fact may not carry a
pattern anything can apply, so the schema-rule-plus-facts design has a ceiling
of the ground fraction: 12.6% here and **0%** externally.

⭐ What (4) settles is that shape diversity was being over-counted. Arity grows
by exactly one per composition with a 2-member rule, and the join graph comes
from the pieces -- so a 7-member rule is not a novel shape, it is a composite.
The primitive inventory is two, and they are already 75.5% of what is authored.

⚠⚠ **DO NOT GATE ANYTHING ON THE EXTERNAL CORPORA.** They belong to sibling
repositories that track other refs, and (2) is skipped with a note when they are
absent. A missing sibling is not a failure here and must never become one.
"""
import contextlib
import glob
import io
import os
import sys
from collections import Counter
from typing import Optional

from .machine import Machine
from . import text
from . import rules as R

# Sibling corpora, relative to this repository. Absent is normal.
EXTERNAL = ("../pystrider/restrider/rules/*.ugm", "../harneskills_new/corpus/*.ugm")

_fine: Counter = Counter()
_coarse: Counter = Counter()
_coarsest: Counter = Counter()
_tally = {"machines": 0, "rules": 0, "bundled": 0, "authored": 0,
          "generic": 0, "ground": 0}


def _vars(g, node) -> frozenset:
    return frozenset(text._vars_in(g, node))


def _shapes(g, r):
    """Three granularities, because the answer depends on which you ask.

    ⚠ The FINE key includes the join graph, which makes every large rule unique
    by construction -- that is what over-counted external shapes as novel. It is
    kept because the comparison between the three is the finding.
    """
    vs = [_vars(g, m.pattern) for m in r.antecedent]
    pairs = [(i, j) for i in range(len(vs)) for j in range(i + 1, len(vs)) if vs[i] & vs[j]]
    joined = bool(pairs)
    asigns = ",".join(m.sign for m in r.antecedent)
    con = ",".join(m.sign + ("VAR" if g.is_var(m.pattern) else "p") for m in r.consequent)
    fine = (f"{r.connective} | ant {len(r.antecedent)}[{asigns}]"
            f"{' join ' + '+'.join(f'{i}-{j}' for i, j in pairs) if pairs else ' nojoin'}"
            f" | con [{con}]")
    coarse = (f"{r.connective} ant[{''.join(sorted(m.sign for m in r.antecedent))}]"
              f"{' joined' if joined else ''} -> con[{con}]")
    coarsest = (f"{r.connective} ant-signs{sorted({m.sign for m in r.antecedent})} "
                f"con-signs{sorted({m.sign for m in r.consequent})}")
    return fine, coarse, coarsest


def _count(m: Machine, authored_only: bool = True) -> None:
    g = m.g
    bundled = {x.node for x in m.bundle}
    _tally["machines"] += 1
    for r in m.rules.rules:
        _tally["rules"] += 1
        if r.node in bundled:
            _tally["bundled"] += 1
            continue
        _tally["authored"] += 1
        fine, coarse, coarsest = _shapes(g, r)
        _fine[fine] += 1
        _coarse[coarse] += 1
        _coarsest[coarsest] += 1
        generic = (any(text._vars_in(g, x.pattern) for x in r.antecedent)
                   or any(text._vars_in(g, x.pattern) for x in r.consequent))
        _tally["generic" if generic else "ground"] += 1


def install() -> None:
    run = Machine.run

    def counted(self, limit=100):
        # ⚠ A flag on the machine, never a set of id() -- `ugm.harmony` records
        # why: an address is reused the moment a machine is collected, and that
        # census under-reported by 3.5x without anything looking wrong.
        if not getattr(self, "_shape_censused", False):
            self._shape_censused = True
            _count(self)
        return run(self, limit)

    Machine.run = counted


# -- 3. what the surface will express ---------------------------------------

PROBES = (
    ("a fact may carry a variable",
     "fact +hinged(?x)", False),
    ("...but a NAMED one may",
     "fact <nh> = forbidden(doing(harm(?x)))", True),
    ("a whole proposition as an argument",
     "fact achieves(travel(work), at(work))", True),
    ("a bare-variable consequent",
     "rule <r> = implies( { +did(?a), +achieves(?a, ?y) }, { +?y } )", True),
    ("construct a relation from a variable",
     "rule <r> = implies( { +rel(?p, ?x) }, { +?p(?x) } )", False),
    ("§12's skeleton -- `where ?n = succ(?m)`",
     "rule <r> = implies( where ?n = succ(?m) given { +a(?m) } then { +b(?n) } )", False),
    ("§12's named entry / explicit locus",
     "rule <r> = causes( { +pour(?w, ?g) }, { ?e = entry(?m, level(?g), ?) } )", False),
    ("§11's span as a locus",
     "rule <r> = implies( { +a(?m) }, { entry(span(?m, ?n), rises(level(g)), +) } )", False),
    ("§16's change-term, held",
     "rule <r> = causes( { +pour(?w, ?g) }, { ? level(?g), +rises(level(?g)) } )", True),
)


def _probe() -> int:
    """⭐ The wall, measured rather than read. A fact CAN carry a pattern when it
    is named; nothing can APPLY one, because deciding a stored `hinged(?x)`
    corresponds to a ground `hinged(gate)` is match, and match is floor (§5).
    That is the ceiling on schema-rules-plus-facts, and it is why the ground
    fraction above is the number that matters.
    """
    bad = 0
    print("3. WHAT THE SURFACE EXPRESSES")
    for label, src, want in PROBES:
        m = Machine()
        try:
            text.load(m, src)
            got = True
        except Exception:
            got = False
        mark = "ok  " if got == want else "CHANGED"
        if got != want:
            bad += 1
        print(f"   {mark} {'accepts' if got else 'refuses'}  {label}")
    # and the one that parses and does not fire
    m = Machine()
    text.load(m, "fact <ho> = implication(hinged(?x), open(?x))\n"
                 "rule <mp> = implies( { +implication(?p, ?q), +?p }, { +?q } )\n"
                 "fact +hinged(gate)")
    m.run(limit=40)
    fired = any(m.g.show(e.proposition) == "open(gate)"
                for e in m._state() if e.sign == "+")
    if fired:
        bad += 1
    print(f"   {'CHANGED' if fired else 'ok  '} a named fact carrying an implication "
          f"parses and does NOT fire -- §5's wall")
    return bad


# -- 4. arity and joins are generated ---------------------------------------

TARGET = ("rule <target> = implies( { +p0(?a,?b), +p1(?a,?c), +p2(?a,?d), "
          "+p3(?b,?c), +p4(?c,?d) }, { +q(?a) } )")

PIECES = """
rule <k0> = implies( { +p0(?a,?b) },                   { +i0(?a,?b) } )
rule <k1> = implies( { +i0(?a,?b), +p1(?a,?c) },       { +i1(?a,?b,?c) } )
rule <k2> = implies( { +i1(?a,?b,?c), +p2(?a,?d) },    { +i2(?a,?b,?c,?d) } )
rule <k3> = implies( { +i2(?a,?b,?c,?d), +p3(?b,?c) }, { +i3(?a,?c,?d) } )
rule <k4> = implies( { +i3(?a,?c,?d), +p4(?c,?d) },    { +i4(?a) } )
rule <k5> = implies( { +i4(?a) },                      { +q(?a) } )
"""


def _sig(m, r):
    """Members and join graph, named by relation so two rules are comparable."""
    rel = lambda x: m.g.show(x.pattern).split("(")[0]
    vs = [_vars(m.g, x.pattern) for x in r.antecedent]
    joins = sorted(tuple(sorted((rel(r.antecedent[i]), rel(r.antecedent[j]))))
                   for i in range(len(vs)) for j in range(i + 1, len(vs)) if vs[i] & vs[j])
    return sorted(rel(x) for x in r.antecedent), joins


def _composition() -> int:
    """⭐ A dense, NON-PATH join graph, generated by composing 2-member rules.

    Arity grows by exactly one per composition with a 2-member rule, and the
    joins come from the pieces -- so a high-arity rule is a COMPOSITE, not a
    novel shape. The scaffolding (`i0`..`i4`) does not survive into the result,
    which is what makes this an authoring mechanism rather than an optimisation:
    §22 lists *nothing can be surprised inside a shortcut* as a cost, and here
    it is the point, because the intermediates were never claims.
    """
    bad = 0
    print("4. ARITY AND JOINS ARE GENERATED, NOT PRIMITIVE")
    m = Machine(); text.load(m, TARGET)
    tgt = next(r for r in m.rules.rules if r.name == "target")
    t_rels, t_joins = _sig(m, tgt)

    m2 = Machine(); text.load(m2, PIECES)
    by = {r.name: r for r in m2.rules.rules if r.name}
    acc = by["k0"]
    for k in ("k1", "k2", "k3", "k4", "k5"):
        acc = m2.rules.compose(acc, by[k], name=f"acc_{k}")
        if acc is None:
            print(f"   CHANGED compose returned nothing at {k}")
            return 1
    c_rels, c_joins = _sig(m2, acc)
    left = sum(1 for x in acc.antecedent if m2.g.show(x.pattern).startswith("i"))

    for label, ok in (("members identical", t_rels == c_rels),
                      ("join graph identical", t_joins == c_joins),
                      ("no scaffolding survives", left == 0)):
        print(f"   {'ok  ' if ok else 'CHANGED'} {label}")
        if not ok:
            bad += 1
    print(f"        target   arity {len(tgt.antecedent)}, {len(t_joins)} join edges")
    print(f"        composed arity {len(acc.antecedent)}, {len(c_joins)} join edges, "
          f"from 6 pieces of arity <= 2")

    # ...and the connective, which is a JUDGEMENT made in one line (§22).
    print("   -- composing ACROSS connectives, for the record:")
    for a_conn, b_conn in (("implies", "implies"), ("causes", "causes"),
                           ("implies", "causes"), ("causes", "implies")):
        m3 = Machine()
        text.load(m3, f"rule <x> = {a_conn}( {{ +p(?a) }}, {{ +i(?a) }} )\n"
                      f"rule <y> = {b_conn}( {{ +i(?a), +r(?a) }}, {{ +q(?a) }} )")
        b3 = {r.name: r for r in m3.rules.rules if r.name}
        out = m3.rules.compose(b3["x"], b3["y"], name="c")
        print(f"        {a_conn:7} + {b_conn:7} -> {out.connective if out else 'REFUSED'}")
    return bad


# -- 2. external corpora ----------------------------------------------------

def _external() -> None:
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    files = []
    for pat in EXTERNAL:
        files.extend(sorted(glob.glob(os.path.join(here, pat))))
    print("2. EXTERNAL CORPORA (different authors, different domains)")
    if not files:
        # ⚠ Absent is normal and is NOT a failure. These are sibling
        # repositories tracking other refs; nothing here may gate on them.
        print("   none present -- skipped (this is not a failure)")
        return
    fine, coarsest = Counter(), Counter()
    gen = ground = 0
    sizes = Counter()
    loaded = failed = 0
    for f in files:
        m = Machine()
        try:
            text.load_file(m, f)
        except Exception as e:
            failed += 1
            print(f"   (skipped {os.path.basename(f)}: {type(e).__name__})")
            continue
        loaded += 1
        b = {x.node for x in m.bundle}
        for r in m.rules.rules:
            if r.node in b:
                continue
            fi, _, co = _shapes(m.g, r)
            fine[fi] += 1; coarsest[co] += 1
            sizes[len(r.antecedent)] += 1
            if (any(text._vars_in(m.g, x.pattern) for x in r.antecedent)
                    or any(text._vars_in(m.g, x.pattern) for x in r.consequent)):
                gen += 1
            else:
                ground += 1
    tot = gen + ground
    if not tot:
        print("   nothing loaded")
        return
    print(f"   files {loaded} loaded, {failed} skipped;  rules {tot}")
    print(f"   GENERIC {gen} ({100*gen/tot:.1f}%)   ground {ground} ({100*ground/tot:.1f}%)"
          f"   <- the ceiling on schema-rules-plus-facts")
    print(f"   antecedent sizes {dict(sorted(sizes.items()))}")
    print(f"   shapes: {len(fine)} fine (near-unique -- these are COMPOSITES), "
          f"{len(coarsest)} coarsest")
    for s, n in coarsest.most_common():
        print(f"      {n:4} {100*n/tot:5.1f}%  {s}")


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    install()
    import ugm.selftest as st
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        try:
            st.main()
        except SystemExit:
            pass
    suite = [l for l in buf.getvalue().splitlines() if "checks" in l]

    print("1. INTERNAL CENSUS -- every corpus the suite exercises")
    print(f"   suite: {suite[-1] if suite else '(no count)'}")
    a = _tally["authored"]
    print(f"   machines {_tally['machines']}   rules {_tally['rules']}   "
          f"bundled {_tally['bundled']}   authored {a}")
    if a:
        print(f"   GENERIC {_tally['generic']} ({100*_tally['generic']/a:.1f}%)   "
              f"ground {_tally['ground']} ({100*_tally['ground']/a:.1f}%)")
        print(f"   shapes: {len(_fine)} fine, {len(_coarse)} coarse, "
              f"{len(_coarsest)} coarsest")
        for k in (1, 3, 5, 10):
            cov = sum(n for _, n in _fine.most_common(k))
            print(f"      top {k:2} fine shapes cover {100*cov/a:5.1f}%")
        print("   the two PRIMITIVES, as a share of authored rules:")
        prim = 0
        for s, n in _coarse.most_common(2):
            prim += n
            print(f"      {n:5} {100*n/a:5.1f}%  {s}")
        print(f"      {prim:5} {100*prim/a:5.1f}%  together")
    print()
    _external()
    print()
    bad = _probe()
    print()
    bad += _composition()
    print()
    print(f"{len(PROBES)+1} expressibility probes, 3 composition checks, "
          f"{bad} changed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
