"""Can an agent set itself the goals it learns from? (§16, §19)

`ugm.learning` closes with a cost it could not pay off: an agent learns the
route that harms by TAKING it. It paid in a jug. This file asks whether it has
to.

    python -m ugm.learning.practice

The proposal is one rule and no machinery:

    rule <practise> = implies( { +achieves(?a, ?y) }, { +suppose(goal(?y), certain) } )

A corpus already says what its acts bring about, because `<outcome>` needs
`achieves` to substitute an action with its effect. Read that fact the other way
round and it names something the agent knows how to want. So the goals are
generated by the corpus's own vocabulary, exactly as `induce`'s tests are, and
nothing here is a curriculum somebody wrote.

⭐⭐⭐ **What makes it safe is already built, and it is the whole reason this is
five rules of fixture rather than a subsystem.** §16's supposition boundary keys
on `doing`: inside a frame entered by supposing, deciding to act deposits
`taken(x)` instead of `emitted(x)`, and `<outcome>` carries the reasoning past
the act by its assumed effect. So a rehearsal runs to the end -- routes taken,
jugs broken, goals lost -- with **nothing leaving the agent**. Measured below,
and kill-probed: propose the goal bare instead of supposing it and the jug
really breaks.

⭐⭐⭐ **And what it costs is ticks.** Round 0 smashes the jug, regrets it,
learns to attend the tap, and round 1 onward fills the kettle -- all of it
inside the frame. Then the agent goes into the world and gets it right the first
time. Nobody wrote an explore rule and none is used.

⚠⚠⚠ **This file used to make a bigger claim than that, and the claim went
with its world.** It ran in a world where BOTH routes harmed, one twice as
badly, and the finding was that the oscillation `ugm.learning` files as a defect
is exploration when it happens inside a supposition -- *the same behaviour, and
which one it is depends only on where the agent is standing.* That rested on
`prefer`, which names a rule and can therefore separate two routes that are
about the same things. An attention lesson names a NODE and cannot: where both
routes hold their vessel, nothing lifts one and not the other, so nothing is
learned in that world and there is no oscillation to reinterpret. See
`learning.the_lesser_of_two_evils_is_unsayable`.

The world here is `ugm.learning`'s own -- a tap and a jug -- where the routes
are about different things and the better one was there to be passed up. So
what a rehearsal buys is not exploration; it is **regret, paid for in ticks
instead of in jugs**, which is the smaller claim and the one that survives.

⚠⚠⚠ **The proposer nests, and that is the one thing here that needs a guard
rather than a reading.** `<practise>` matches inside a practice frame as readily
as outside one, so a corpus with two achievable relations opens
`supposing(goal(water(kettle)))` *inside* `supposing(goal(lit(room)))`. Reading
the inner frame's cost off `current_state` charges it for the outer one's
damage. §4's two times are half a repair and cost no new bookkeeping -- an entry
is this frame's doing iff its locus is at-or-after the frame's origin -- and
measured, that does drop the parent's loss.

⚠⚠⚠ **Only half, and the other half is why the guard is not optional.** Which
half you get is decided by where the proposer is authored. When the parent's
damage predates the inner frame, the origin test excludes it. When it does not,
the inner rehearsal **re-derives it** from inherited state -- `<light>` applies
again inside the nested frame -- and the loss is then deposited by the inner
frame, at its own moment, licensed by its own application. No test on loci can
tell that from the route's own doing, because it is not distinguishable: under
that hypothesis the damage really is done. Both orders are run below and both
are gated, because a single order would have reported a repair that works.

That leaves the nesting bounded only by `_enacted` refusing to suppose one
proposition twice -- an accident of identity, not a guard.

⚠ **A rehearsal can only discover harms the corpus can state.** Delete the rule
that says what breaking the jug costs and practice concludes the jug is free,
confidently and from evidence. That is the third time a fixture has been unable
to express the very thing it was checking, so it is a gate, not a caveat -- and
the gate carries what the mute world taught into a world that CAN say the cost,
because a world with nothing to lose reports an agent that lost nothing.
"""

from typing import List, Optional, Sequence, Tuple

from ..core.chain import MINUS
from ..core.machine import Machine, induce, leaves
from .learning import BASE as WORLD_RULES, JUG, TAP
from ..core.text import load

PRACTISE = ("rule <practise> = implies( { +achieves(?a, ?y) },"
            " { +suppose(goal(?y), certain) } )")
# The kill-probe for containment: the same proposer with the supposition taken
# out. Everything else is identical, so what it measures is the frame.
BARE = "rule <practise> = implies( { +achieves(?a, ?y) }, { +goal(?y) } )"

# The world is `ugm.learning`'s, minus the one line that hands the agent its
# goal. That deletion IS the experiment: `goal(water(kettle))` is authored
# nowhere below, and if the agent practises anything it is because it worked out
# what it could want. It is written as a filter rather than an omission so the
# deletion is visible in the source.
WANTED = "fact +goal(water(kettle))"
BASE = [line for line in WORLD_RULES + [
    "fact +achieves(fill(kettle), water(kettle))",
    "fact +achieves(smash(jug1), water(kettle))",
    "fact +tap(sink)", "fact +under(kettle, sink)",
    "fact +jug(jug1)", "fact +holds(jug1, kettle)", "fact +intact(jug1)",
    "fact +fruit(orange)",
    # ⚠ A PRESERVATION goal, and the fixture does not work without one. Blame
    # attributes a LOST goal, so a world where nothing is wanted to stay as it
    # is has no way to say the jug mattered -- the same gap the mute world at
    # the end of this file measures, arriving from the other side.
    "fact +goal(intact(jug1))",
    WANTED,
] if line != WANTED]
BAD_START = [JUG, TAP]   # the jug route first: the costly one wins on order
LOSSES = ("intact(jug1)",)
COSTS = ("rule <cost> = implies( { +did(smash(?j)) }, { -intact(?j) } )",)

# A second achievable relation, so the proposer can be shown raising more than
# one goal -- and so the nesting has somewhere to happen. ⚠ The second rehearsal
# must COST something (`-dark(room)`, wanted), or a nested rehearsal cannot be
# over-charged and the check below would be unable to fail. That is the whole
# reason `<light>` and `goal(dark(room))` are here.
SECOND = ["rule <use-match> = implies( { +goal(lit(?r)), +match(?m) },"
          " { +doing(strike(?m)) } )",
          "rule <light> = implies( { +did(strike(?m)) }, { -dark(room) } )",
          "fact +achieves(strike(match), lit(room))", "fact +match(match)",
          "fact +dark(room)", "fact +goal(dark(room))"]
WIDER = LOSSES + ("dark(room)",)


def _supposition_frames(m: Machine) -> List:
    """Every frame the proposer opened, wherever it opened it.

    Walked rather than read off `focus.children`, because the proposer nests and
    a rehearsal one level down is still a rehearsal.
    """
    out, frontier = [], [m.focus]
    while frontier:
        f = frontier.pop()
        if f.purpose is not None and m.g.relation_of(f.purpose) is m.SUPPOSING:
            out.append(f)
        frontier.extend(f.children)
    return out


def _own_losses(m: Machine, kb, frame, losses: Sequence[str] = LOSSES) -> List[str]:
    """What THIS rehearsal cost, charged to the frame that incurred it.

    The `at_or_after` test is §4's locus and deposit doing the work they were
    separated for. Without it a nested rehearsal inherits its parent's damage and
    reports it as its own, which reads as a route being twice as expensive as it
    is -- and reads, from outside, exactly like a finding.
    """
    return [g for g, own in _charge(m, kb, frame, losses) if own]


def _charge(m: Machine, kb, frame, losses: Sequence[str] = LOSSES
            ) -> List[Tuple[str, bool]]:
    """Every loss a frame can SEE, and whether it is the frame's own doing.

    Both readings from one walk, so the gate that compares them is not built out
    of the function it is checking -- the difference between the two lists is
    what `_own_losses` claims to remove, and a check that recomputed the filter
    could only ever agree with itself.
    """
    out = []
    for g in losses:
        e = m.chain.resolve(kb.term(g), frame.topic, frame.seat)
        if e is not None and e.sign == MINUS:
            out.append((g, e.locus.at_or_after(frame.origin)))
    return out


def rehearse(rows: Sequence[str] = (), order: Sequence[str] = BAD_START,
             base: Optional[Sequence[str]] = None, proposer: str = PRACTISE,
             extra: Sequence[str] = (), losses: Sequence[str] = LOSSES,
             first: bool = True) -> Tuple[Machine, List, List[str]]:
    """One practice run: the agent works out what it could want, and tries it.

    Returns the machine with its register left standing **inside** the rehearsal.
    That is not a convenience -- `blame`, `leaves` and `harm_of` all read from
    where the reader is standing, and where this reasoning happened is inside the
    frame. Restoring the register before reviewing it would ask the question from
    a place that, by §17's containment, can see none of the answer.
    """
    m = Machine()
    m.actuator("hands")
    src = list(order) + list(BASE if base is None else base)
    # ⚠ Where the proposer is authored decides which rehearsal opens first, and
    # `first=False` is not a variant for completeness -- it is the only order in
    # which the nesting check below can fail. See the two readings in `main`.
    src += [proposer] + list(extra) if first else list(extra) + [proposer]
    kb = load(m, "\n".join(src + list(rows) + [""]))
    m.run(limit=6000)
    m.kb = kb  # the instrument's own handle, so a gate can resolve by name
    frames = _supposition_frames(m)
    lost: List[str] = []
    for f in frames:
        lost.extend(_own_losses(m, kb, f, losses))
    if frames:
        m.focus = frames[0]
    return m, frames, lost


def episode(rows: Sequence[str] = (), order: Sequence[str] = BAD_START,
            base: Optional[Sequence[str]] = None):
    """One run IN THE WORLD: the goal handed over, nothing supposed.

    The comparison every headline here is against -- what the agent does when it
    has not practised. `WANTED` is put back, because this is the case where
    somebody asked for the water.
    """
    m = Machine()
    m.actuator("hands")
    kb = load(m, chr(10).join(list(order) + list(BASE if base is None else base)
                              + [WANTED] + list(rows) + [""]))
    m.run(limit=6000)
    return (m, [m.g.show(n) for n in m.emitted],
            [g for g in LOSSES if m.holds(kb.term(g)) == MINUS])


def practise(rounds: int = 4, order: Sequence[str] = BAD_START,
             base: Optional[Sequence[str]] = None) -> Tuple[List[int], List[str]]:
    """Rehearse, review, carry forward, rehearse again -- and never act.

    The cost `induce` prunes against is measured by **re-rehearsing**, so the
    learner never touches the world at all. Every number this function knows was
    paid for in ticks.
    """
    eps: List[Machine] = []
    seq: List[int] = []
    rows: List[str] = []

    def cost(candidate) -> int:
        return len(rehearse(candidate, order, base)[2])

    for _ in range(rounds):
        m, _, lost = rehearse(rows, order, base)
        eps.append(m)
        seq.append(len(lost))
        rows = induce(eps, cost)
    return seq, rows


def main() -> int:
    import sys

    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    failing = 0
    ran = 0

    def gate(name: str, ok: bool) -> None:
        nonlocal failing, ran
        ran += 1
        print(f"  {'ok  ' if ok else 'FAIL'}  {name}")
        if not ok:
            failing += 1

    print(__doc__.strip().split("\n")[0])
    print()

    # -- the proposer ------------------------------------------------------
    print("A goal nobody authored, raised from what the corpus says acts achieve:\n")
    m, frames, lost = rehearse()
    for f in frames:
        print(f"    {f.state:<12} {m.g.show(f.purpose)}")
    print()
    gate("the goal it practises is authored NOWHERE in the corpus",
         not any("goal(water(kettle))" in line for line in BAD_START + BASE))
    gate("...and the agent raised it anyway, from `achieves`",
         any("supposing(goal(water(kettle)))" == m.g.show(f.purpose) for f in frames))

    multi, mframes, _ = rehearse(extra=SECOND, losses=WIDER)
    raised = {multi.g.show(f.purpose) for f in mframes}
    gate("one goal per achievable relation, so the proposer is not a one-trick",
         len(raised) == 2 and any("lit(room)" in r for r in raised))

    # -- containment -------------------------------------------------------
    print("\nWhat it cost, and where it was paid:\n")
    print(f"  {'rehearsal':<22} {'emitted':<24} lost")
    print(f"  {'supposed':<22} {str([m.g.show(n) for n in m.emitted]):<24} {lost}")
    bm = Machine()
    bm.actuator("hands")
    bkb = load(bm, "\n".join(BAD_START + BASE + [BARE, ""]))
    bm.run(limit=6000)
    bare_acts = [bm.g.show(n) for n in bm.emitted]
    bare_lost = [g for g in LOSSES if bm.holds(bkb.term(g)) == MINUS]
    print(f"  {'proposed bare':<22} {str(bare_acts):<24} {bare_lost}")
    print()
    gate("⭐⭐⭐ a rehearsal costs the agent NOTHING -- it takes a route, breaks "
         "what the route breaks, and nothing leaves", not m.emitted and bool(lost))
    gate("...and the kill-probe shows the frame is what does it: propose the "
         "same goal bare and the jug really breaks",
         bool(bare_acts) and bool(bare_lost))
    gate("the reasoning does not stop at the act -- the route's outcome is "
         "reached under the hypothesis, or there is nothing to cost",
         any(m.g.show(n).startswith("taken(") for n in
             [e.proposition for mo in m.chain.moments for e in mo.delta]))

    # -- it is still a choice ---------------------------------------------
    taken = [m.g.show(e.proposition) for mo in m.chain.moments for e in mo.delta
             if m.g.show(e.proposition).startswith("taken(")]
    forgone = [m.g.show(e.proposition) for mo in m.chain.moments for e in mo.delta
               if m.g.show(e.proposition).startswith("forgone(")]
    print(f"  taken   {taken}")
    print(f"  forgone {forgone}")
    print()
    # ⚠⚠⚠ **DISTINCT routes, not occasions.** This read `len(forgone) == 1` and
    # broke when the attention queue changed how many moves the rehearsal takes:
    # the same route was passed up twice, on two moments, and `_forgo` writes
    # directly with no dedupe because *this happened here* is what an entry
    # says. Two records of one alternative is not two alternatives, and the
    # claim being made is about the CHOICE -- one route taken, one other named.
    # Counting deposits was measuring the length of the run.
    gate("⭐ forgoing works inside a supposition, so a rehearsal is a CHOICE -- "
         "one route taken, the other passed up and named (%d record(s) of it)"
         % len(forgone),
         len(taken) == 1 and len(set(forgone)) == 1)

    # -- practice, and the exploration nobody wrote ------------------------
    print("\nFour rehearsals, each loading what the last one worked out:\n")
    seq, rows = practise()
    print(f"  supposed harm per round   {seq}")
    for r in rows:
        print(f"    {r}")
    print()
    gate("⭐⭐⭐ the first rehearsal costs a jug and the rest cost nothing -- the "
         "agent found the better route and paid for it in ticks", seq[0] > seq[1])
    gate("...and it stays found: no oscillation, because the route it wanted "
         "was there to be passed up all along", len(set(seq[1:])) == 1)
    gate("no `<venture>` rule and no explore/exploit switch anywhere",
         not any("venture" in r or "exploring" in r for r in rows))
    gate("what it carries out names the TAP -- the thing that makes the cheaper "
         "route available -- and no rule id at all",
         any("attention(" in r for r in rows)
         and not any("prefer(" in r for r in rows))

    # -- the headline ------------------------------------------------------
    print("\nThe world, for real, from the bad start -- ONE run each:\n")
    print(f"  {'agent':<26} {'emitted':<20} lost")
    naive_m, naive_acts, naive_lost = episode()
    prac_m, prac_acts, prac_lost = episode(rows)
    print(f"  {'no practice':<26} {str(naive_acts):<20} {naive_lost}")
    print(f"  {'practised first':<26} {str(prac_acts):<20} {prac_lost}")
    print()
    gate("the control can fail: an unpractised agent from a bad start takes the "
         "costly route", naive_lost == ["intact(jug1)"])
    gate("⭐⭐⭐ the practised agent gets it right the FIRST time in the world, "
         "and the knowledge was paid for in ticks",
         len(prac_lost) < len(naive_lost))
    gate("...and it is not merely doing less -- the goal is still achieved",
         prac_m.holds(prac_m.g.rel(prac_m.g.atom("water"),
                                   prac_m.g.atom("kettle"))) is not None
         or bool(prac_acts))

    # -- nesting, measured rather than assumed -----------------------------
    print("\nThe proposer inside its own rehearsal:\n")
    def shape(f, d=0):
        p = multi.g.show(f.purpose) if f.purpose is not None else "<root>"
        print(f"    {'   ' * d}{f.state or 'root':<12} {p[:52]}")
        for c in f.children:
            shape(c, d + 1)
    shape(mframes[0].ancestry()[-1])
    print()
    nested = [f for f in mframes if any(
        a.purpose is not None and multi.g.relation_of(a.purpose) is multi.SUPPOSING
        for a in f.ancestry()[1:])]
    gate("⚠⚠⚠ `<practise>` matches inside a practice frame, so rehearsals NEST "
         "-- the crossing runaway in a new place", bool(nested))
    gate("⚠ it is bounded only because a proposition cannot be supposed twice, "
         "not because anything guards it", multi.exhausted == 0)

    # The two readings, in both authoring orders. Reported rather than asserted:
    # the claim is a DIFFERENCE, and a check that recomputed the filter would
    # agree with itself whatever the frames did.
    print("    the inner rehearsal's bill, by where the proposer is authored:")
    print(f"      {'proposer':<10} {'charged by what it SEES':<52} its OWN")
    readings = {}
    for label, first in (("first", True), ("last", False)):
        mm, ff, _ = rehearse(extra=SECOND, losses=WIDER, first=first)
        deep = [f for f in ff if len(f.ancestry()) > 2]
        if not deep:
            continue
        charge = _charge(mm, mm.kb, deep[0], WIDER)
        seen = [g for g, _ in charge]
        own = [g for g, o in charge if o]
        readings[label] = (seen, own)
        print(f"      {label:<10} {str(seen):<52} {own}")
    print()
    gate("⚠⚠⚠ the inherited reading OVER-CHARGES a nested rehearsal -- it bills "
         "the inner frame for a loss its PARENT's rehearsal caused",
         any(len(s) > len(o) for s, o in readings.values()))
    gate("⭐ and §4's origin test removes exactly that: what it drops is the "
         "parent's loss, what it keeps is the route's own",
         any(set(s) - set(o) == {"dark(room)"} and "intact(jug1)" in o
             for s, o in readings.values()))
    gate("⚠⚠⚠ ...but only when the parent's damage PREDATES the frame. In the "
         "other order the inner rehearsal RE-DERIVES it from inherited state, "
         "and no test on loci can tell re-derivation from doing -- so nesting "
         "needs a guard, not a cleverer reading",
         any(len(s) == len(o) for s, o in readings.values()))

    # -- a world that cannot state its costs -------------------------------
    print("\nThe same practice, in a world that cannot say what the vase cost:\n")
    mute = [line for line in BASE if line not in COSTS]
    mute_seq, mute_rows = practise(base=mute)
    _, mute_acts, mute_lost = episode(mute_rows, base=mute)
    # ⚠⚠⚠ The damage is INVISIBLE, not absent, and the difference is the whole
    # point -- so what the mute rehearsal learned is carried into the world that
    # CAN state the cost. Reading `mute_lost` alone would report a world with
    # nothing to lose as an agent that lost nothing.
    _, carried_acts, carried_lost = episode(mute_rows)
    print(f"  supposed harm per round   {mute_seq}")
    print(f"  in the world afterwards   {mute_acts} lost {mute_lost}")
    print(f"  what it learned, in the world that CAN say the cost   "
          f"{carried_acts} lost {carried_lost}")
    print()
    gate("⚠⚠⚠ practice teaches nothing when the world cannot express the "
         "damage -- it rehearses, observes no cost, and learns the costly "
         "route is free", sum(mute_seq) < sum(seq) and not mute_rows)
    gate("...and the agent is no better off than the one that never practised: "
         "carry what the mute world taught into one that can say what a jug "
         "costs, and it breaks the jug",
         carried_acts == naive_acts and carried_lost == naive_lost)

    print(f"\n{ran} checks, {failing} failing")
    print("""
  ⭐⭐⭐ A GOAL IS ALREADY IN THE CORPUS, WRITTEN THE OTHER WAY ROUND. `achieves`
  exists so `<outcome>` can substitute an action with its effect; read from the
  right it names something the agent knows how to want. One rule turns it into a
  curriculum, and the curriculum is the corpus's own vocabulary -- the same
  answer `induce` gave for where a learned rule's TESTS come from, arriving a
  second time for where its GOALS come from.

  ⭐⭐⭐ REGRET IS AFFORDABLE WHEN IT IS PAID IN TICKS. The agent smashes the jug,
  regrets it, learns to attend the tap, and does none of it in the world.
  Nothing was added to get that -- the boundary that makes it safe shipped for a
  different reason (§16), and forgoing works inside a frame without being told
  to.

  ⚠⚠⚠ AND A BIGGER CLAIM WENT WITH ITS WORLD. This file used to run where both
  routes harmed and report that oscillation and exploration are the same
  behaviour seen from different places. That needed a lesson that could separate
  two routes ABOUT THE SAME THINGS, which is what naming a rule could do and
  naming a node cannot. Nothing is learned in that world now, so there is no
  oscillation to reinterpret. The finding is not refuted; it is unsayable, which
  is a different thing and is recorded as one.

  ⚠⚠⚠ THE PROPOSER NESTS, AND A READING CANNOT FIX IT. `<practise>` matches
  inside a practice frame, so rehearsals open inside rehearsals. §4's origin test
  removes the parent's damage from the inner frame's bill and costs no new
  bookkeeping, and on one authoring order that is the whole repair. On the other
  the inner frame RE-DERIVES the parent's loss from inherited state and deposits
  it itself -- own moment, own licence -- and nothing about a locus separates
  that from the route's own doing, because under that hypothesis it is not
  separate. Both orders are gated; one alone would have reported a fix.

  > **A containment question answered by reading is answered only for the
  > orders you happened to run.**

  The guard this wants is the one §16 already uses for effects: ask whether any
  frame on the path was entered by supposing. That is machinery, and making it a
  corpus's to state is untried -- `-goal(?y)` does not express it, because §9's
  `-` is *an entry denies this* and never *no entry*.

  ⚠ WHAT THIS DOES NOT SHOW. Practice is only as honest as the world's cost
  rules -- gated above, because a fixture that cannot express the harm reports
  confident nonsense rather than nothing. And the nesting is bounded here only by
  `_enacted` refusing a proposition twice, which is an accident of identity: a
  corpus whose acts achieve enough distinct things meets the depth bound instead,
  and nothing here would say so.

  ⚠ Nor does it choose WHAT to rehearse. Every achievable relation is practised,
  which is affordable for one corpus and is not a policy. The design already has
  the shape of the answer -- `dormant(<domain>)` gates what is even considered --
  and joining the two is untried.""")
    return 1 if failing else 0


if __name__ == "__main__":
    raise SystemExit(main())
